- name: add ssh key for simone
  authorized_key:
     user: simone
     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHiMfkDKk+LeUy4peWNlAaKMIddn6GL/RXEp/mR81nTb Ansible"
- name: openssh | generate sshd_config file from template
  tags: ssh
  template:
     src: "{{ ssh_template_file }}"
     dest: /etc/ssh/sshd_config
     owner: root
     group: root
     mode: 0644
  notify: restart_sshd